runtime: java11
instance_class: F2
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5

env_variables:
  CLOUD_SQL_CONNECTION_NAME: "astute-diode-435514-g7:asia-south1-a:jeanspant"
  DB_USER: "root"
  DB_PASS: "bota@lali@123"
  DB_NAME: "denty"

handlers:
  # Static file handlers
  - url: /static
    static_dir: static/

  # Main application (Servlets/JSP)
  - url: /.*
    script: auto